### ISSUE TITLE
User Profile Page Mock-up

### ISSUE THREAD

**Issue by ivan-iliev** [DevDatesDevelopers/Front-End-Mockup#10]
[Link to Figma Design](https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1). The User Profile Page allows the logged in user to see his/her profile descriptions, pictures interests and other. **SEE THE FIGMA DESIGN FOR MORE DETAILS**

**Comment by Kardam-Simeonov** [comment]
<div class="bg-primary rounded-full aspect-square w-[4.5rem] flex items-center justify-center">
          <Icon icon="fa6-solid:x" class="text-3xl aspect-square" />
</div>`

**Comment by ktodorov-itarea** [comment]
Защо не е отбелезано като завършено?
