### ISSUE TITLE
Register(second page) Gender Picker Page

### ISSUE THREAD

**Issue by Kardam-Simeonov** [DevDatesDevelopers/Front-End-Mockup#12]
[Link to figma design](https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1). The Gender Picker Page allows the user to choose between three options for a gender. SEE THE FIGMA DESIGN FOR MORE DETAILS

![image](https://user-images.githubusercontent.com/72763706/223706901-04f674eb-1c74-45b8-b851-e82995c1b552.png)

**Comment by ktodorov-itarea** [comment]
Защо не е затворено?

**Comment by Kardam-Simeonov** [comment]
Погледни документацията на Vue JS. DOM манипулация на Vue проект няма как да работи. Рефакторираи логиката на Javascript-а на Vue JS

**Comment by Kardam-Simeonov** [comment]
fixed by #21
