### ISSUE TITLE
Home Page Mock-up

### ISSUE THREAD

**Issue by ivan-iliev** [DevDatesDevelopers/Front-End-Mockup#3]
[Link to figma file](https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1) Home page must show the slide functionality between user profiles and have the ability to view a user's profile on demand

**Comment by Kardam-Simeonov** [comment]
[https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1](Link to figma design)

**Comment by ktodorov-itarea** [comment]
Защо не е отбелязано като завършено?
