### ISSUE TITLE
Sign Up Page Mock-up

### ISSUE THREAD

**Issue by ivan-iliev** [DevDatesDevelopers/Front-End-Mockup#4]
[Link to Figma Design](https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1). Sign up page must allow a user to be able to sign up with an email and a password. **SEE THE FIGMA DESIGN FOR MORE DETAILS**

[Icon Link](https://icones.js.org/)

![Image](https://user-images.githubusercontent.com/72763706/223704615-c7107f11-e178-4203-91fb-68bf71f89013.png)

**Comment by ktodorov-itarea** [comment]
Това защо не е отбелязано като завършено?
