### ISSUE TITLE
Start(Log In) Page Mock-up

### ISSUE THREAD

**Issue by ivan-iliev** [DevDatesDevelopers/Front-End-Mockup#8]
[Link to Figma Design](https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1). Start screen must include the login form, as well as a link to the Sign up page. **SEE THE FIGMA DESIGN FOR MORE DETAILS**

![image](https://user-images.githubusercontent.com/72763706/223703438-f0e80dbc-df87-4949-bf08-0d0eb6f29024.png)

**Comment by ktodorov-itarea** [comment]
Защо не е отбелязано като завършено?
