### ISSUE TITLE
Interests Page Mock-up

### ISSUE THREAD

**Issue by ivan-iliev** [DevDatesDevelopers/Front-End-Mockup#9]
[Link to figma design](https://www.figma.com/file/E8XzelLB9kZhnPWMGwzOeV/DevDatesDesign?node-id=0%3A1&t=FhGGhX6nfyW5zRTq-1). Interests page allows the user to pick interests. **SEE THE FIGMA DESIGN FOR MORE DETAILS**

![image](https://user-images.githubusercontent.com/72763706/223705874-fda2a569-0121-4fa0-839f-9c1e6410f64f.png)

**Comment by ktodorov-itarea** [comment]
Защо не е отбелязано като завършено?
